### ISSUE TITLE
Tool no longer tracking win-rates, economic data and Draft Helper is not working

### ISSUE THREAD

**Issue by EdwardCYC** [Manuel-777/MTG-Arena-Tool#561]
Hello. After the season reset on 1st September, I logged into MTG Arena Tool and realised that the Draft Helper had all the card grades at F. It was also no longer tracking my win rates nor my economic data (event pool, booster pack opening).

Here are some images for reference (Sept 6 rewards were due to a previous bug):

![](https://puu.sh/EctPa/4315ef61e2.png)

![image](https://user-images.githubusercontent.com/50830952/64109912-43b0a180-cdb3-11e9-9678-a8ecd3f68a2d.png)

**Comment by Manuel-777** [comment]
The ranks have been fixed already , however the economy might be an unrelated issue. Check in Settings > Arena Data that your timestamp is correct

**Comment by EdwardCYC** [comment]
I tried leaving the Log Timestamp Format empty, and also tried 'dd/mm/yyyy hh:mm:ss aa`, but it still does not read it correctly.

![image](https://user-images.githubusercontent.com/50830952/64180770-ef332200-ce97-11e9-9993-65bd33584fe7.png)

What's the correct format for this?

**Comment by EdwardCYC** [comment]
Solved it. Just needed to remove the AM/PM formatting. **dd/mm/yyyy hh:mm:ss** works.
