### ISSUE TITLE
Update to 2.12.6 fails

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#671]
Windows setup; while previous updates were having no issues, the 2.12.6 fails to update.
If trying to update from the About section in the application, it download the update one time and then show this:

![update_error](https://user-images.githubusercontent.com/709500/67671552-766fb400-f976-11e9-8e76-22be1ceef741.PNG)
Next tries just fetch metadata and fails to do anything more.

I also tried to restart the application, and it indeed download the update on startup, but then still start the 2.12.5 without installing the new update.
It also did shown this error message after startup. I guess this is related but can't know:
![TLS_error](https://user-images.githubusercontent.com/709500/67671639-9ef7ae00-f976-11e9-9922-a21f04428f16.PNG)

This setup being a windows computer, no idea how and if I can gather more information.

EDIT: Connection works flawlessly.

**Comment by Porkepix** [comment]
Update to 2.12.8 had no issue, therefore I don't know what caused the issue.

Now I see that 2.12.6 is a pre-release, but I'm almost sure it was tagged as a normal release back then, and the application was indeed seeing an update to do and tried to download and install it.

Should this issue be closed, or get further investigations?

**Comment by Manuel-777** [comment]
Yes, this was fixed, it was an issue with the release tags in v2.12.7.

**Comment by Porkepix** [comment]
@Manuel-777 Same issue is back with update from 2.14.0 to 2.14.2.
